import Button from '../../../../design-system/components/Button/Button.jsx';
import Input from '../../../../design-system/components/Input/Input.jsx';
import Label from '../../../../design-system/components/Label/Label.jsx';
import { FIELD_TYPES } from '../../../../core/data/entityType.js';

export default function DesignerFieldEditor({ field, index, total, fieldTypes, entityTypes, listSelected, onChange, onMove, onRemove, onToggleList }) {
  const prefix = `designer-${field._designerId}`;
  return <article className="rounded-xl border border-neutral-200 bg-white p-4" aria-label={`Field ${index + 1}: ${field.label || 'Untitled'}`}>
    <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-medium uppercase text-neutral-500">Field {index + 1}</p><p className="font-medium text-neutral-900">{field.label || 'Untitled field'}</p></div><div className="flex flex-wrap gap-1"><Button type="button" variant="ghost" size="sm" disabled={index === 0} onClick={() => onMove(-1)} aria-label={`Move ${field.label || `field ${index + 1}`} up`}>Move up</Button><Button type="button" variant="ghost" size="sm" disabled={index === total - 1} onClick={() => onMove(1)} aria-label={`Move ${field.label || `field ${index + 1}`} down`}>Move down</Button><Button type="button" variant="ghost" size="sm" onClick={onRemove} aria-label={`Remove ${field.label || `field ${index + 1}`}`}>Remove</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label htmlFor={`${prefix}-label`}>Label</Label><Input id={`${prefix}-label`} value={field.label} onChange={(event) => onChange({ label: event.target.value })} /></div><div><Label htmlFor={`${prefix}-key`}>Stable field key</Label><Input id={`${prefix}-key`} value={field.key} onChange={(event) => onChange({ key: event.target.value })} /></div><div><Label htmlFor={`${prefix}-type`}>Field type</Label><select id={`${prefix}-type`} value={field.type} onChange={(event) => onChange({ type: event.target.value })} className="w-full rounded-md border border-neutral-300 px-3 py-2 text-sm">{fieldTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><div className="flex flex-col justify-end gap-2 pb-2"><label className="flex items-center gap-2 text-sm text-neutral-700"><input type="checkbox" checked={field.required} onChange={(event) => onChange({ required: event.target.checked })} />Required</label><label className="flex items-center gap-2 text-sm text-neutral-700"><input type="checkbox" checked={listSelected} disabled={!field.key} onChange={onToggleList} />Show in Record List</label></div></div>
    <div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`${prefix}-placeholder`}>Placeholder</Label><Input id={`${prefix}-placeholder`} value={field.placeholder} onChange={(event) => onChange({ placeholder: event.target.value })} /></div><div><Label htmlFor={`${prefix}-help`}>Help text</Label><Input id={`${prefix}-help`} value={field.helpText} onChange={(event) => onChange({ helpText: event.target.value })} /></div></div>
    {field.type === FIELD_TYPES.SELECT && <div className="mt-3"><Label htmlFor={`${prefix}-options`}>Options, one per line</Label><textarea id={`${prefix}-options`} rows={5} value={field.optionsText} onChange={(event) => onChange({ optionsText: event.target.value })} placeholder={'OPEN\nIN_PROGRESS\nCOMPLETED'} className="w-full rounded-md border border-neutral-300 px-3 py-2 text-sm" /></div>}
    {field.type === FIELD_TYPES.ENTITY_REFERENCE && <div className="mt-3"><Label htmlFor={`${prefix}-entity-type`}>Referenced Entity Type</Label><select id={`${prefix}-entity-type`} value={field.entityTypeId} onChange={(event) => onChange({ entityTypeId: event.target.value })} className="w-full rounded-md border border-neutral-300 px-3 py-2 text-sm"><option value="">Choose Entity Type</option><optgroup label="Core Entity Types">{entityTypes.filter((item) => item.category === 'CORE').map((item) => <option key={item.typeId} value={item.typeId}>{item.name} ({item.code})</option>)}</optgroup><optgroup label="Domain Entity Types">{entityTypes.filter((item) => item.category === 'DOMAIN').map((item) => <option key={item.typeId} value={item.typeId}>{item.name} ({item.code})</option>)}</optgroup></select></div>}
    {field.type === FIELD_TYPES.NUMBER && <div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`${prefix}-min`}>Minimum</Label><Input id={`${prefix}-min`} type="number" value={field.min} onChange={(event) => onChange({ min: event.target.value })} /></div><div><Label htmlFor={`${prefix}-max`}>Maximum</Label><Input id={`${prefix}-max`} type="number" value={field.max} onChange={(event) => onChange({ max: event.target.value })} /></div></div>}
    {[FIELD_TYPES.TEXT, FIELD_TYPES.TEXTAREA].includes(field.type) && <div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`${prefix}-min-length`}>Minimum length</Label><Input id={`${prefix}-min-length`} type="number" min="0" value={field.minLength} onChange={(event) => onChange({ minLength: event.target.value })} /></div><div><Label htmlFor={`${prefix}-max-length`}>Maximum length</Label><Input id={`${prefix}-max-length`} type="number" min="0" value={field.maxLength} onChange={(event) => onChange({ maxLength: event.target.value })} /></div></div>}
  </article>;
}
