const text = (key, label, required = false) => ({ key, label, type: 'text', required });
const textarea = (key, label, required = false) => ({ key, label, type: 'textarea', required });
const date = (key, label, required = false) => ({ key, label, type: 'date', required });
const bool = (key, label, required = false) => ({ key, label, type: 'boolean', required });
const select = (key, label, options, required = false) => ({ key, label, type: 'select', options, required });
const entityRef = (key, label, entityTypeId, required = true) => ({ key, label, type: 'entity-reference', entityTypeId, required });
const fileRef = (key, label) => ({ key, label, type: 'file-reference', required: false });
const area = (code, name, description, importance = 'HIGH') => ({ areaRef: `businessArea:${code}`, code, name, description, importance, domainObjectRefs: [], processRefs: [], capabilityRefs: [], rationale: description });
const object = (code, name, classification, rationale, entityTypeRef = null, coreEntityCode = null) => ({ objectRef: `domainObject:${code}`, code, name, classification, rationale, entityTypeRef, coreEntityCode });
const process = (code, name, areaCode, objectRefs, moduleCode, stages) => ({ processRef: `process:${code}`, code, name, businessAreaRef: `businessArea:${areaCode}`, description: name, participants: [], inputObjectRefs: objectRefs, outputObjectRefs: objectRefs, trigger: 'Operational need', mainStages: stages, exceptions: [], frequency: 'Recurring', capabilityRefs: ['capability:FORM_CAPTURE', 'capability:STATUS_TRACKING'], recommendedModuleRefs: [`module:${moduleCode}`] });
const module = (code, name, areaCode, processCode, fields, capabilities = ['records', 'reports', 'widgets']) => ({ ref: `module:${code}`, moduleCode: code, name, description: `${name} operational workflow`, category: areaCode, businessAreaRef: `businessArea:${areaCode}`, processRef: `process:${processCode}`, recordType: code, capabilities, formSchema: { schemaVersion: '1.0.0', fields }, displayConfig: { primaryField: fields[0]?.key || null, listFields: fields.slice(0, 4).map((field) => field.key) }, lifecycle: ['DRAFT', 'SUBMITTED', 'COMPLETED', 'CANCELLED'], ledgerRequirements: null, rationale: `Supports ${name.toLowerCase()} operations.` });
const workset = (code, name, moduleCodes) => ({ ref: `workset:${code}`, name, description: `${name} working context`, moduleRefs: moduleCodes.map((item) => `module:${item}`), rationale: 'Groups related Modules for operational context; it does not grant access.' });
const widget = (code, name, moduleCode) => ({ ref: `widget:${code}`, name, moduleRefs: [`module:${moduleCode}`], definition: { type: 'KPI', source: 'RECORDS', metric: 'COUNT', filters: [], display: { limit: 10 } }, rationale: `Provides a bounded count for ${name.toLowerCase()}.` });
const report = (code, name, moduleCode) => ({ ref: `report:${code}`, name, definition: { dataSources: [{ sourceType: 'RECORDS', moduleRef: `module:${moduleCode}` }], filters: [], groupBy: [], metrics: [{ type: 'COUNT', key: 'count' }], columns: [], sort: [], visualization: { type: 'TABLE' } }, rationale: `Summarizes ${name.toLowerCase()}.` });
const capabilities = [
  { capabilityRef: 'capability:FORM_CAPTURE', code: 'FORM_CAPTURE', supported: true },
  { capabilityRef: 'capability:ENTITY_REFERENCE', code: 'ENTITY_REFERENCE', supported: true },
  { capabilityRef: 'capability:STATUS_TRACKING', code: 'STATUS_TRACKING', supported: true },
  { capabilityRef: 'capability:DATE_TRACKING', code: 'DATE_TRACKING', supported: true },
  { capabilityRef: 'capability:FILE_ATTACHMENT', code: 'FILE_ATTACHMENT', supported: true },
  { capabilityRef: 'capability:REPORTING', code: 'REPORTING', supported: true },
  { capabilityRef: 'capability:WIDGET_VISUALIZATION', code: 'WIDGET_VISUALIZATION', supported: true },
];

export const INDUSTRY_KNOWLEDGE = Object.freeze([
  {
    code: 'HOSPITALITY_HOTEL', industry: 'Hospitality', organizationType: 'Hotel', keywords: ['hotel', 'room', 'guest', 'restaurant', 'parking', 'housekeeping'],
    businessAreas: [area('FRONT_OFFICE', 'Front Office', 'Reservations, arrivals, stays and guest service.'), area('HOUSEKEEPING', 'Housekeeping', 'Room readiness, cleaning and inspection.'), area('MAINTENANCE', 'Maintenance', 'Facility and equipment issue resolution.'), area('FOOD_BEVERAGE', 'Food & Beverage', 'Restaurant and service operations.', 'MEDIUM'), area('PARKING', 'Parking', 'Parking capacity and guest access.', 'MEDIUM'), area('MANAGEMENT', 'Management', 'Operational oversight and reporting.')],
    domainObjects: [object('ROOM', 'Room', 'DOMAIN_ENTITY', 'Rooms are persistent identities shared across reservations, housekeeping and maintenance.', 'entityType:ROOM'), object('GUEST', 'Guest', 'CORE_REUSE', 'Guest identity can reuse the CUSTOMER/PERSON Core concept.', null, 'CUSTOMER'), object('RESERVATION', 'Reservation', 'RECORD_DATA', 'A reservation is operational process data with lifecycle and dates.'), object('STAY', 'Stay', 'RECORD_DATA', 'A stay is operational process data linked to a Room and Guest.'), object('EQUIPMENT', 'Equipment', 'CORE_REUSE', 'Hotel equipment reuses the Core EQUIPMENT type.', null, 'EQUIPMENT')],
    entityTypes: [{ ref: 'entityType:ROOM', code: 'ROOM', name: 'Room', description: 'Hotel room identity', fields: [text('roomNumber', 'Room number', true), select('roomType', 'Room type', ['Standard', 'Deluxe', 'Suite'], true), select('operationalStatus', 'Operational status', ['AVAILABLE', 'OCCUPIED', 'OUT_OF_SERVICE'], true)] }],
    processes: [process('RESERVATION_LIFECYCLE', 'Reservation lifecycle', 'FRONT_OFFICE', ['domainObject:ROOM', 'domainObject:GUEST', 'domainObject:RESERVATION'], 'RESERVATION', ['Capture request', 'Confirm room and dates', 'Update status']), process('GUEST_CHECK_IN', 'Guest check-in', 'FRONT_OFFICE', ['domainObject:ROOM', 'domainObject:GUEST', 'domainObject:STAY'], 'CHECK_IN', ['Verify reservation', 'Assign room', 'Record arrival']), process('ROOM_HOUSEKEEPING', 'Room housekeeping', 'HOUSEKEEPING', ['domainObject:ROOM'], 'HOUSEKEEPING', ['Assign cleaning', 'Record condition', 'Mark readiness']), process('MAINTENANCE_REQUEST', 'Maintenance request', 'MAINTENANCE', ['domainObject:ROOM', 'domainObject:EQUIPMENT'], 'MAINTENANCE', ['Report issue', 'Assign priority', 'Resolve and verify'])],
    modules: [module('RESERVATION', 'Reservation', 'FRONT_OFFICE', 'RESERVATION_LIFECYCLE', [entityRef('room', 'Room', 'entityType:ROOM'), text('guestName', 'Guest name', true), date('arrivalDate', 'Arrival date', true), date('departureDate', 'Departure date', true), select('reservationStatus', 'Reservation status', ['REQUESTED', 'CONFIRMED', 'CANCELLED'], true), textarea('specialRequests', 'Special requests')]), module('CHECK_IN', 'Guest Check-in', 'FRONT_OFFICE', 'GUEST_CHECK_IN', [entityRef('room', 'Room', 'entityType:ROOM'), text('guestName', 'Guest name', true), date('arrivalDate', 'Arrival date', true), bool('identityVerified', 'Identity verified', true), textarea('notes', 'Arrival notes')]), module('HOUSEKEEPING', 'Housekeeping', 'HOUSEKEEPING', 'ROOM_HOUSEKEEPING', [entityRef('room', 'Room', 'entityType:ROOM'), date('serviceDate', 'Service date', true), select('condition', 'Room condition', ['CLEAN', 'NEEDS_ATTENTION', 'OUT_OF_SERVICE'], true), bool('followUpRequired', 'Follow-up required'), textarea('issues', 'Issues found'), fileRef('photos', 'Photos')]), module('MAINTENANCE', 'Maintenance Request', 'MAINTENANCE', 'MAINTENANCE_REQUEST', [entityRef('room', 'Room', 'entityType:ROOM', false), text('equipmentReference', 'Equipment reference'), textarea('issue', 'Issue', true), select('priority', 'Priority', ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], true), date('reportedDate', 'Reported date', true), bool('resolved', 'Resolved'), fileRef('attachments', 'Attachments')])],
    relationships: [], worksets: [workset('FRONT_DESK', 'Front Desk', ['RESERVATION', 'CHECK_IN']), workset('HOUSEKEEPING', 'Housekeeping', ['HOUSEKEEPING']), workset('MAINTENANCE', 'Maintenance', ['MAINTENANCE'])], widgets: [widget('ARRIVALS', "Today's Arrivals", 'CHECK_IN'), widget('ROOMS_CLEANING', 'Rooms Awaiting Cleaning', 'HOUSEKEEPING'), widget('OPEN_MAINTENANCE', 'Open Maintenance Requests', 'MAINTENANCE')], reports: [report('RESERVATION_SUMMARY', 'Reservation Summary', 'RESERVATION'), report('HOUSEKEEPING_ACTIVITY', 'Housekeeping Activity', 'HOUSEKEEPING'), report('MAINTENANCE_ACTIVITY', 'Maintenance Activity', 'MAINTENANCE')],
    assumptions: ['One primary hotel location is planned initially.', 'Payroll and restaurant inventory are outside the initial plan.'], questions: [{ code: 'RESTAURANT_SCOPE', category: 'OPTIONAL_REFINEMENT', question: 'Should restaurant inventory and purchasing be included in the initial system?' }, { code: 'PARKING_SCOPE', category: 'OPTIONAL_REFINEMENT', question: 'Should parking spaces be managed individually or only as capacity?' }], terminology: ['room', 'guest', 'reservation', 'stay'],
  },
  {
    code: 'PERFORMING_ARTS_THEATRE', industry: 'Performing Arts', organizationType: 'Theatre', keywords: ['theatre', 'theater', 'show', 'actor', 'rehearsal', 'performance', 'costume', 'props', 'lighting', 'sound'],
    businessAreas: [area('PRODUCTIONS', 'Productions', 'Production planning and delivery.'), area('REHEARSALS', 'Rehearsals', 'Rehearsal schedules and reports.'), area('PERFORMANCES', 'Performances', 'Live performance operations.'), area('STAGE', 'Stage Management', 'Stage, lighting and sound coordination.'), area('WARDROBE_PROPS', 'Costumes & Props', 'Costume and prop readiness and movement.'), area('FRONT_OF_HOUSE', 'Front of House', 'Venue and audience operations.')],
    domainObjects: [object('PRODUCTION', 'Production', 'DOMAIN_ENTITY', 'A production persists across rehearsals and performances.', 'entityType:PRODUCTION'), object('PERFORMANCE', 'Performance', 'DOMAIN_ENTITY', 'A scheduled performance has a stable identity.', 'entityType:PERFORMANCE'), object('REHEARSAL', 'Rehearsal', 'RECORD_DATA', 'Rehearsal reports are operational records.'), object('PERSON', 'Cast and Crew', 'CORE_REUSE', 'Actors and crew reuse PERSON/EMPLOYEE.', null, 'PERSON'), object('EQUIPMENT', 'Lighting and Sound Equipment', 'CORE_REUSE', 'Technical assets reuse EQUIPMENT.', null, 'EQUIPMENT')],
    entityTypes: [{ ref: 'entityType:PRODUCTION', code: 'PRODUCTION', name: 'Production', description: 'Theatre production identity', fields: [text('title', 'Title', true), date('openingDate', 'Opening date')] }, { ref: 'entityType:PERFORMANCE', code: 'PERFORMANCE', name: 'Performance', description: 'Scheduled live performance', fields: [entityRef('production', 'Production', 'entityType:PRODUCTION'), date('performanceDate', 'Performance date', true)] }],
    processes: [process('REHEARSAL_REPORTING', 'Rehearsal reporting', 'REHEARSALS', ['domainObject:PRODUCTION', 'domainObject:REHEARSAL'], 'REHEARSAL_REPORT', ['Schedule', 'Run rehearsal', 'Capture notes']), process('SHOW_REPORTING', 'Performance show reporting', 'PERFORMANCES', ['domainObject:PRODUCTION', 'domainObject:PERFORMANCE'], 'SHOW_REPORT', ['Prepare venue', 'Run performance', 'Record show report']), process('COSTUME_PROP_TRACKING', 'Costume and prop readiness', 'WARDROBE_PROPS', ['domainObject:PRODUCTION'], 'COSTUME_PROP_CHECK', ['Prepare items', 'Check readiness', 'Record issues']), process('TECHNICAL_CHECK', 'Lighting and sound technical check', 'STAGE', ['domainObject:EQUIPMENT'], 'TECHNICAL_CHECK', ['Inspect equipment', 'Test cues', 'Record faults'])],
    modules: [module('REHEARSAL_REPORT', 'Rehearsal Report', 'REHEARSALS', 'REHEARSAL_REPORTING', [entityRef('production', 'Production', 'entityType:PRODUCTION'), date('rehearsalDate', 'Rehearsal date', true), text('stageManager', 'Stage manager', true), textarea('castNotes', 'Cast and crew notes'), textarea('technicalNotes', 'Technical notes')]), module('SHOW_REPORT', 'Performance Show Report', 'PERFORMANCES', 'SHOW_REPORTING', [entityRef('performance', 'Performance', 'entityType:PERFORMANCE'), date('showDate', 'Show date', true), select('showStatus', 'Show status', ['COMPLETED', 'CANCELLED', 'INTERRUPTED'], true), textarea('incidents', 'Incidents'), textarea('audienceNotes', 'Front of house notes')]), module('COSTUME_PROP_CHECK', 'Costume & Prop Check', 'WARDROBE_PROPS', 'COSTUME_PROP_TRACKING', [entityRef('production', 'Production', 'entityType:PRODUCTION'), select('itemArea', 'Area', ['COSTUME', 'PROP'], true), text('itemName', 'Item name', true), select('readiness', 'Readiness', ['READY', 'REPAIR_REQUIRED', 'MISSING'], true), textarea('notes', 'Notes'), fileRef('photos', 'Photos')]), module('TECHNICAL_CHECK', 'Lighting & Sound Check', 'STAGE', 'TECHNICAL_CHECK', [entityRef('production', 'Production', 'entityType:PRODUCTION'), select('department', 'Department', ['LIGHTING', 'SOUND'], true), date('checkDate', 'Check date', true), select('result', 'Result', ['PASS', 'ISSUES_FOUND'], true), textarea('issues', 'Issues')])],
    relationships: [{ ref: 'relationship:PRODUCTION_PERFORMANCE', sourceRef: 'entityType:PRODUCTION', targetRef: 'entityType:PERFORMANCE', relationshipType: 'HAS_PERFORMANCE' }], worksets: [workset('STAGE_MANAGEMENT', 'Stage Management', ['REHEARSAL_REPORT', 'SHOW_REPORT', 'TECHNICAL_CHECK']), workset('WARDROBE_PROPS', 'Costumes & Props', ['COSTUME_PROP_CHECK'])], widgets: [widget('UPCOMING_SHOWS', 'Upcoming Shows', 'SHOW_REPORT'), widget('TECHNICAL_ISSUES', 'Technical Issues', 'TECHNICAL_CHECK')], reports: [report('SHOW_SUMMARY', 'Show Summary', 'SHOW_REPORT'), report('REHEARSAL_ACTIVITY', 'Rehearsal Activity', 'REHEARSAL_REPORT')], assumptions: ['Ticket sales are outside the initial operational plan.'], questions: [{ code: 'RIGHTS_SCOPE', category: 'OPTIONAL_REFINEMENT', question: 'Should rights and licensing tracking be included?' }], terminology: ['production', 'performance', 'rehearsal', 'cast', 'crew', 'props', 'costumes'],
  },
  {
    code: 'EDUCATION_SCHOOL', industry: 'Education', organizationType: 'School', keywords: ['school', 'student', 'teacher', 'classroom', 'course', 'attendance', 'private school'],
    businessAreas: [area('ACADEMICS', 'Academics', 'Students, classes and courses.'), area('ATTENDANCE', 'Attendance', 'Daily student attendance.'), area('INCIDENTS', 'Student Incidents', 'Incident reporting and follow-up.'), area('FACILITIES', 'Facilities', 'Classrooms and shared equipment.'), area('COMMUNICATION', 'Parent Communication', 'Structured communication follow-up.')],
    domainObjects: [object('STUDENT', 'Student', 'DOMAIN_ENTITY', 'Students are persistent school identities.', 'entityType:STUDENT'), object('CLASS', 'Class', 'DOMAIN_ENTITY', 'Classes persist across attendance and incidents.', 'entityType:CLASS'), object('COURSE', 'Course', 'DOMAIN_ENTITY', 'Courses define academic offerings.', 'entityType:COURSE'), object('TEACHER', 'Teacher', 'CORE_REUSE', 'Teachers reuse PERSON/EMPLOYEE.', null, 'EMPLOYEE'), object('ROOM', 'Classroom', 'CORE_REUSE', 'Classrooms can reuse LOCATION.', null, 'LOCATION'), object('EQUIPMENT', 'Shared Equipment', 'CORE_REUSE', 'Shared assets reuse EQUIPMENT.', null, 'EQUIPMENT')],
    entityTypes: [{ ref: 'entityType:STUDENT', code: 'STUDENT', name: 'Student', description: 'Student identity', fields: [text('studentNumber', 'Student number', true), text('displayName', 'Display name', true)] }, { ref: 'entityType:CLASS', code: 'CLASS', name: 'Class', description: 'Class identity', fields: [text('classCode', 'Class code', true), text('className', 'Class name', true)] }, { ref: 'entityType:COURSE', code: 'COURSE', name: 'Course', description: 'Course identity', fields: [text('courseCode', 'Course code', true), text('courseName', 'Course name', true)] }],
    processes: [process('DAILY_ATTENDANCE', 'Daily attendance', 'ATTENDANCE', ['domainObject:STUDENT', 'domainObject:CLASS'], 'ATTENDANCE', ['Select class', 'Record attendance', 'Submit']), process('STUDENT_INCIDENT', 'Student incident handling', 'INCIDENTS', ['domainObject:STUDENT'], 'STUDENT_INCIDENT', ['Report incident', 'Assign follow-up', 'Resolve']), process('EQUIPMENT_CHECK', 'Shared equipment check', 'FACILITIES', ['domainObject:EQUIPMENT'], 'EQUIPMENT_CHECK', ['Inspect equipment', 'Record condition', 'Escalate issues'])],
    modules: [module('ATTENDANCE', 'Student Attendance', 'ATTENDANCE', 'DAILY_ATTENDANCE', [entityRef('student', 'Student', 'entityType:STUDENT'), entityRef('class', 'Class', 'entityType:CLASS'), date('attendanceDate', 'Attendance date', true), select('attendanceStatus', 'Status', ['PRESENT', 'ABSENT', 'LATE', 'EXCUSED'], true), textarea('notes', 'Notes')]), module('STUDENT_INCIDENT', 'Student Incident', 'INCIDENTS', 'STUDENT_INCIDENT', [entityRef('student', 'Student', 'entityType:STUDENT'), date('incidentDate', 'Incident date', true), select('severity', 'Severity', ['LOW', 'MEDIUM', 'HIGH'], true), textarea('description', 'Description', true), bool('parentContactRequired', 'Parent contact required'), textarea('followUp', 'Follow-up')]), module('EQUIPMENT_CHECK', 'Equipment Check', 'FACILITIES', 'EQUIPMENT_CHECK', [text('equipmentReference', 'Equipment reference', true), date('checkDate', 'Check date', true), select('condition', 'Condition', ['GOOD', 'REPAIR_REQUIRED', 'UNSAFE'], true), textarea('issues', 'Issues'), fileRef('photos', 'Photos')])],
    relationships: [{ ref: 'relationship:CLASS_COURSE', sourceRef: 'entityType:CLASS', targetRef: 'entityType:COURSE', relationshipType: 'USES_COURSE' }], worksets: [workset('TEACHING', 'Teaching', ['ATTENDANCE', 'STUDENT_INCIDENT']), workset('FACILITIES', 'Facilities', ['EQUIPMENT_CHECK'])], widgets: [widget('ATTENDANCE_TODAY', "Today's Attendance", 'ATTENDANCE'), widget('OPEN_INCIDENTS', 'Open Student Incidents', 'STUDENT_INCIDENT')], reports: [report('ATTENDANCE_SUMMARY', 'Attendance Summary', 'ATTENDANCE'), report('INCIDENT_SUMMARY', 'Incident Summary', 'STUDENT_INCIDENT')], assumptions: ['Timetable generation and grading are outside the initial plan.'], questions: [{ code: 'PARENT_COMMUNICATION_SCOPE', category: 'OPTIONAL_REFINEMENT', question: 'Should parent communication workflows be included initially?' }], terminology: ['student', 'teacher', 'class', 'course', 'attendance'],
  },
]);

export function resolveIndustryKnowledge(input) {
  const textValue = [input.organizationName, input.description, input.industry, input.userDescription, ...(input.services || []), ...(input.facilities || [])].filter(Boolean).join(' ').toLowerCase();
  const ranked = INDUSTRY_KNOWLEDGE.map((profile) => ({ profile, score: profile.keywords.reduce((score, keyword) => score + (textValue.includes(keyword) ? 1 : 0), 0) })).sort((left, right) => right.score - left.score);
  if (!ranked[0] || ranked[0].score === 0) throw new Error('The organization description is not specific enough to select an operating-domain knowledge profile.');
  return ranked[0].profile;
}

export { capabilities as PLATFORM_CAPABILITIES };
