import Alert from '../../../design-system/components/Alert/Alert.jsx';
import Card from '../../../design-system/components/Card/Card.jsx';

const classificationFor = (plan, ref) => plan.validation?.classifications?.find((item) => item.ref === ref)?.operation || 'CREATE';

function Section({ title, count, children, open = false }) {
  return <details open={open} className="rounded-lg border border-neutral-200 bg-white"><summary className="cursor-pointer px-4 py-3 font-semibold text-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-500">{title} <span className="text-sm font-normal text-neutral-500">({count})</span></summary><div className="border-t border-neutral-100 p-4">{children}</div></details>;
}

export default function AutomatPlanReview({ result }) {
  const { plan, review } = result;
  return <div className="space-y-4" data-testid="automat-plan-review">
    <Alert variant="info">No changes have been applied to this Workspace. This plan is ready for human review only.</Alert>
    <Card><h2 className="text-xl font-semibold text-neutral-900">Organization summary</h2><p className="mt-2 text-neutral-700">{plan.organizationProfile.organizationType} · {plan.industryAnalysis.industry}</p><p className="mt-1 text-sm text-neutral-600">{plan.industryAnalysis.rationale}</p><div className="mt-3 flex flex-wrap gap-2 text-sm text-neutral-600"><span>Business areas: {review.diagnostics.businessAreasCovered}</span><span>Processes: {review.diagnostics.processesCovered}</span><span>Business objects: {review.diagnostics.domainObjectsCovered}</span></div></Card>
    <Section title="Business Areas" count={plan.businessAreas.length} open><div className="grid gap-3 md:grid-cols-2">{plan.businessAreas.map((item) => <article key={item.areaRef} className="rounded-md bg-neutral-50 p-3"><h3 className="font-medium text-neutral-900">{item.name}</h3><p className="mt-1 text-sm text-neutral-600">{item.description}</p><p className="mt-2 text-xs font-medium uppercase text-neutral-500">{item.importance} importance</p></article>)}</div></Section>
    <Section title="Business Objects" count={plan.domainObjects.length}><div className="grid gap-3 md:grid-cols-2">{plan.domainObjects.map((item) => <article key={item.objectRef} className="rounded-md bg-neutral-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium text-neutral-900">{item.name}</h3><span className="rounded-full bg-primary-50 px-2 py-1 text-xs text-primary-700">{item.classification.replaceAll('_', ' ')}</span></div><p className="mt-1 text-sm text-neutral-600">{item.rationale}</p>{item.coreEntityCode && <p className="mt-1 text-xs text-neutral-500">Reuses Core: {item.coreEntityCode}</p>}</article>)}</div></Section>
    <Section title="Processes" count={plan.processes.length}><div className="space-y-3">{plan.processes.map((item) => <article key={item.processRef} className="rounded-md bg-neutral-50 p-3"><h3 className="font-medium text-neutral-900">{item.name}</h3><p className="mt-1 text-sm text-neutral-600">{item.mainStages.join(' → ')}</p></article>)}</div></Section>
    <Section title="Modules" count={plan.proposedModules.length} open><div className="space-y-3">{plan.proposedModules.map((item) => <article key={item.ref} className="rounded-md border border-neutral-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-medium text-neutral-900">{item.name}</h3><p className="font-mono text-xs text-neutral-500">{item.moduleCode}</p></div><span className="rounded-full bg-primary-50 px-2 py-1 text-xs font-medium text-primary-700">{classificationFor(plan, item.ref)}</span></div><p className="mt-2 text-sm text-neutral-600">{item.rationale}</p><ul className="mt-2 grid gap-1 text-sm text-neutral-700 sm:grid-cols-2">{item.formSchema.fields.map((field) => <li key={field.key}>{field.label} <span className="text-neutral-400">· {field.type}</span></li>)}</ul></article>)}</div></Section>
    <Section title="Worksets" count={plan.proposedWorksets.length}><div className="space-y-2">{plan.proposedWorksets.map((item) => <article key={item.ref}><h3 className="font-medium text-neutral-900">{item.name}</h3><p className="text-sm text-neutral-600">{item.moduleRefs.join(', ')}</p></article>)}</div></Section>
    <Section title="Widgets" count={plan.proposedWidgets.length}><ul className="space-y-2">{plan.proposedWidgets.map((item) => <li key={item.ref} className="rounded-md bg-neutral-50 p-3 font-medium text-neutral-800">{item.name}</li>)}</ul></Section>
    <Section title="Reports" count={plan.proposedReports.length}><ul className="space-y-2">{plan.proposedReports.map((item) => <li key={item.ref} className="rounded-md bg-neutral-50 p-3 font-medium text-neutral-800">{item.name}</li>)}</ul></Section>
    <Section title="Warnings" count={plan.warnings.length}>{plan.warnings.length ? <ul className="list-disc space-y-1 pl-5 text-sm text-neutral-700">{plan.warnings.map((item, index) => <li key={item.code || index}>{item.message || item}</li>)}</ul> : <p className="text-sm text-neutral-600">No planning warnings.</p>}</Section>
    <Section title="Questions & Assumptions" count={plan.unresolvedQuestions.length + (plan.organizationProfile.assumptions?.length || 0)}><div className="space-y-3"><ul className="space-y-2">{plan.unresolvedQuestions.map((item) => <li key={item.code}><span className="font-medium text-neutral-800">{item.question}</span><span className="ml-2 text-xs text-neutral-500">{item.category.replaceAll('_', ' ')}</span></li>)}</ul><ul className="list-disc space-y-1 pl-5 text-sm text-neutral-600">{plan.organizationProfile.assumptions?.map((item) => <li key={item}>{item}</li>)}</ul></div></Section>
    <Card><h2 className="font-semibold text-neutral-900">Validation result</h2><p className="text-sm text-neutral-600">{plan.validation.status} · {plan.validation.issues.length} issues</p></Card>
  </div>;
}
